language: python
python: '2.7'
sudo: false
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
addons:
  apt_packages:
    - swig
before_install:
  - python --version
  - uname -a
  - lsb_release -a
  - pip install codecov
install:
  - pip install tox
  - virtualenv --version
  - easy_install --version
  - pip --version
  - gcc --version
  - python setup.py install
script:
  - py.test python/
after_success:
  - codecov
before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
notifications:
  email:
    on_success: never
    on_failure: always
